package de.lathspell.rest.apiproblem;

import java.util.Map;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.Wither;

/**
 * Data Transfer Object for the JSON body of a REST error response.
 *
 * Descriptions are quoted from the specs:
 * http://tools.ietf.org/html/draft-nottingham-http-problem-04
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Wither
public class ApiProblem {

    /**
     * An absolute URI [RFC3986] that identifies the problem type.
     *
     * When dereferenced, it SHOULD provide human-readable documentation
     * for the problem type (e.g., using HTML).
     * REQUIRED.
     */
    private String problemType;

    /**
     * A short, human-readable summary of the problem type.
     *
     * It SHOULD NOT change from occurrence to occurrence of the
     * problem, except for purposes of localisation.
     * REQUIRED.
     */
    private String title;

    /**
     * The HTTP status code ([RFC2616], Section 6) generated by the origin
     * server for this occurrence of the problem.
     *
     * Generators MUST use the same status code in the actual HTTP response.
     * OPTIONAL.
     */
    private Integer httpStatus;

    /**
     * An absolute URI [RFC3986] that identifies the problem type.
     *
     * When dereferenced, it SHOULD provide human-readable documentation
     * for the problem type (e.g., using HTML).
     * OPTIONAL.
     */
    private String detail;

    /**
     * An absolute URI that identifies the specific occurrence of the problem.
     *
     * It may or may not yield further information if dereferenced.
     * OPTIONAL.
     */
    private String problemInstance;

    /**
     * Extension Members.
     *
     * If such additional members are defined, their names SHOULD start with
     * a letter (ALPHA, as per [RFC5234]) and SHOULD consist of characters
     * from ALPHA, DIGIT and "_" (so that it can be serialised in formats
     * other than JSON), and SHOULD be three characters or longer.
     * OPTIONAL.
     */
    private Map<String, String> extras;

}
